const data = {
  products: [
    {
      id: 1,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/imagen01.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality ',
    },
    {
      id: 2,
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/imagen02.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      id: 3,
      name: 'Dress',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/imagen03.jpg',
      price: 25,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      id: 4,
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Dress',
      image: '/images/imagen05.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
